errorlevel -203, -205, 302
LIST P=16F887
#include <P16F887.inc>
;POWER-UP-TIMER ON, WATCH-DOG OFF,OSC XT CRYSTAL 4MHz
__CONFIG _CONFIG1,B'0010000011100001'

ORG 0
GOTO setup

ORG 5
setup			CLRF PORTC				;INICIALIZA PORTC
				BANKSEL PR2				;MODULO DE CCPwm, PWM CONFIG:
				MOVLW .63				;TMR2 PERIODO = 63 -> f=1KHz
				MOVWF PR2
				BANKSEL CCP2CON
				MOVLW B'00001111'		;DUTY CLYCLE Lsb=0, MODO PWM
				MOVWF CCP2CON
				CLRF CCPR2L				;INICIA CON DUTY CYCLE DE 0%
				BANKSEL TMR2
				CLRF PIR1				;INICIALIZA BANDERA DEL TMR2
				CLRF TMR2				;INICIALIZA TMR2
				MOVLW B'00000011'		;PreS = 16, PosS = 1
				MOVWF T2CON
				BSF T2CON,ON			;TMR2 COMIENZA
				BTFSS PIR1,TMR2IF		;ESPERA UN PERIODO DE ESTABILIZACION
				GOTO $-1
				BCF PIR,TMR2IF			;BAJA BANDERA
				BANKSEL TRISC
				BCF TRSC,TRSC1			;PWM SALIDA ACTIVADA
main			GOTO$
END