LIST P=PIC16F887
#INCLUDE <P16F887.INC>

VECES EQU 0X20
ORG 0X00
GOTO INICIO
ORG 0X05
INICIO MOVLW .15
MOVWF VECES
MOVLW 0X40
MOVWF FSR
BACK MOVLW 0X20
MOVWF INDF
INCF FSR
DECFSZ VECES
GOTO BACK ; Se colocaron 15 datos iguales a partir de la posicion 0x40
MOVLW .15
MOVWF VECES
MOVLW 0X40
MOVWF FSR
ATRAS SWAPF INDF,F
MOVLW .3
ADDWF INDF,F
INCF FSR
DECFSZ VECES
GOTO ATRAS
GOTO $ 
END ; manu_bonino@hotmail.com