LIST p=PIC16F887
#include <p16F887.inc>

__CONFIG _CONFIG1, 0x20F4

REP		EQU		0X20

ORG 0x00
GOTO SETUP
ORG 0x04
GOTO INTERR

ORG 0x05
SETUP   	CLRF PORTA
			CLRF PORTB
			MOVLW 0x90
			MOVWF INTCON
			BANKSEL OSCCON
			MOVLW 0x08
			MOVWF OSCCON		
			CLRF TRISA
			MOVLW 0X01
			MOVWF TRISB			
			BANKSEL ANSEL
			CLRF ANSEL
			CLRF ANSELH
			BANKSEL PORTA
			BSF REP,2
			GOTO MAIN

MAIN		CALL RETARDO
			CALL RETARDO		
			ADDWF PORTA,F
			GOTO MAIN

RETARDO		MOVLW 0x00
			ADDLW 0x01
			BTFSS STATUS,C
			GOTO $-2
			RETLW 0x01

INTERR		BTFSS INTCON,INTF
			RETFIE
			BCF INTCON,INTF
L1			MOVLW 0x07
			MOVWF PORTA
			CALL RETARDO
			CALL RETARDO
			CLRF PORTA
			CALL RETARDO
			CALL RETARDO
			DECFSZ REP
			GOTO L1
			RETFIE						
END
		
