errorlevel -205, -203, -302
LIST P=16F887
#include <P16F887.inc>
__CONFIG _CONFIG1, B'10000000100100'

CBLOCK 0X20
	X
	K
	w_temp
	sts_temp
ENDC

#define LED_ON BSF PORTB,RB1
#define LED_OFF BCF PORTB,RB1

ORG 0
GOTO setup
ORG 4 
GOTO INT
ORG 5
setup		CLRF PORTB
			BANKSEL OSCCON
			MOVLW B'00001010'			;LFINOSC f=31KHz, ESTABLE
			MOVWF OSCCON
			BANKSEL ANSELH				;PORTB DIGITAL
			CLRF ANSELH
			BANKSEL TRISB
			BCF TRISB,TRISB1			;PORTB IN RB0, OUT RB1
			BANKSEL OPTION_REG
			MOVLW B'00000111'			;PORTB PULL-UPS, INT POR BAJO, TMR0 PS=256
			MOVWF OPTION_REG			
			BANKSEL INTCON
			CLRF INTCON
			BSF INTCON,T0IE				;INTERRUPCION POR TMR0
			BSF INTCON,INTE				;INTERRUPCIONES POR INT EXTERNA
			BANKSEL X						
			MOVLW 0XFF					;VALORES PARA RETARDO POR SOFTWARE DE 500ms	
			MOVWF X						;
			MOVLW 0X05					;	
			MOVWF K						;
			CLRF TMR0					;TMR0=0
			BSF INTCON,GIE				;COMENZAR A CONTAR

main		LED_ON
			CALL ret500ms
			LED_OFF
			CALL ret500ms
			GOTO main

ret500ms	DECFSZ X					;RETARDO DE 500ms
			GOTO $-1
			DECF X
			DECFSZ K
			GOTO ret500ms
			MOVLW 0X05	
			MOVWF K
			RETURN

INT			BCF INTCON,T0IF				;BAJA BANDERA DE LA INT EXTERNA
			MOVWF w_temp				;DESBORDO EL TMR0 -> SALVA ENTORNO
			SWAPF w_temp,F
			SWAPF STATUS,W
			MOVWF sts_temp
			SLEEP						;HIBERNAR MICRO
			NOP	
			BCF INTCON,INTF				;DESPERTO MICRO -> BAJAR BANDERA DE INT EXT
			SWAPF sts_temp,W			;RECARGA ENTORNO
			MOVWF STATUS
			SWAPF w_temp,W
			RETFIE						;VUELTA AL PROGRAMA
END