/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 15-Oct-2020 12:17:07
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 124
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 124;
const int16_T B[124] = {
       59,    111,     12,    159,      2,    151,     50,     87,    134,
        6,    196,    -29,    184,     15,     88,    114,    -40,    195,
     -116,    180,    -85,     46,     33,   -143,    142,   -275,    132,
     -263,    -40,   -118,   -304,     40,   -509,     57,   -523,   -149,
     -333,   -506,    -86,   -813,     -1,   -863,   -229,   -597,   -715,
     -179,  -1193,     63,  -1325,   -160,   -920,   -887,   -116,  -1799,
      607,  -2289,    572,  -1646,   -986,   1156,  -6382,  19627,  19627,
    -6382,   1156,   -986,  -1646,    572,  -2289,    607,  -1799,   -116,
     -887,   -920,   -160,  -1325,     63,  -1193,   -179,   -715,   -597,
     -229,   -863,     -1,   -813,    -86,   -506,   -333,   -149,   -523,
       57,   -509,     40,   -304,   -118,    -40,   -263,    132,   -275,
      142,   -143,     33,     46,    -85,    180,   -116,    195,    -40,
      114,     88,     15,    184,    -29,    196,      6,    134,     87,
       50,    151,      2,    159,     12,    111,     59
};
