/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 31-Oct-2020 18:21:30
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 192
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 192;
const int16_T B[192] = {
      -35,    -20,     -3,     15,     33,     49,     64,     75,     83,
       86,     84,     78,     67,     52,     33,     11,    -12,    -35,
      -57,    -77,    -93,   -105,   -111,   -111,   -105,    -93,    -75,
      -51,    -24,      5,     36,     65,     93,    116,    134,    145,
      148,    143,    129,    108,     80,     45,      7,    -34,    -75,
     -113,   -147,   -174,   -193,   -202,   -199,   -186,   -160,   -125,
      -80,    -28,     29,     87,    144,    196,    240,    273,    293,
      297,    284,    255,    208,    146,     71,    -15,   -106,   -200,
     -290,   -372,   -440,   -489,   -515,   -513,   -482,   -418,   -321,
     -191,    -30,    159,    372,    603,    846,   1094,   1339,   1575,
     1794,   1989,   2153,   2281,   2369,   2413,   2413,   2369,   2281,
     2153,   1989,   1794,   1575,   1339,   1094,    846,    603,    372,
      159,    -30,   -191,   -321,   -418,   -482,   -513,   -515,   -489,
     -440,   -372,   -290,   -200,   -106,    -15,     71,    146,    208,
      255,    284,    297,    293,    273,    240,    196,    144,     87,
       29,    -28,    -80,   -125,   -160,   -186,   -199,   -202,   -193,
     -174,   -147,   -113,    -75,    -34,      7,     45,     80,    108,
      129,    143,    148,    145,    134,    116,     93,     65,     36,
        5,    -24,    -51,    -75,    -93,   -105,   -111,   -111,   -105,
      -93,    -77,    -57,    -35,    -12,     11,     33,     52,     67,
       78,     84,     86,     83,     75,     64,     49,     33,     15,
       -3,    -20,    -35
};
