/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
 * Generated on: 31-Oct-2020 17:15:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 151
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
const int BL = 151;
const int16_T B[151] = {
       24,     23,     22,     21,     20,     19,     18,     17,     15,
       14,     12,     10,      8,      6,      3,      0,     -3,     -7,
      -11,    -15,    -20,    -25,    -30,    -36,    -42,    -49,    -57,
      -64,    -72,    -81,    -90,   -100,   -110,   -120,   -131,   -142,
     -153,   -165,   -177,   -190,   -203,   -216,   -229,   -242,   -256,
     -270,   -283,   -297,   -311,   -325,   -338,   -352,   -365,   -379,
     -392,   -404,   -417,   -429,   -440,   -451,   -462,   -472,   -482,
     -491,   -500,   -508,   -515,   -521,   -527,   -532,   -537,   -540,
     -543,   -545,   -546,  32246,   -546,   -545,   -543,   -540,   -537,
     -532,   -527,   -521,   -515,   -508,   -500,   -491,   -482,   -472,
     -462,   -451,   -440,   -429,   -417,   -404,   -392,   -379,   -365,
     -352,   -338,   -325,   -311,   -297,   -283,   -270,   -256,   -242,
     -229,   -216,   -203,   -190,   -177,   -165,   -153,   -142,   -131,
     -120,   -110,   -100,    -90,    -81,    -72,    -64,    -57,    -49,
      -42,    -36,    -30,    -25,    -20,    -15,    -11,     -7,     -3,
        0,      3,      6,      8,     10,     12,     14,     15,     17,
       18,     19,     20,     21,     22,     23,     24
};
