/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 31-Oct-2020 18:42:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 83
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 83;
const q15_t B[84] = {
        1,    -44,   -122,   -219,   -317,   -391,   -425,   -409,   -344,
     -244,   -133,    -40,      7,    -10,    -97,   -241,   -414,   -581,
     -700,   -740,   -683,   -534,   -322,    -92,     98,    194,    156,
      -29,   -341,   -726,  -1104,  -1383,  -1472,  -1305,   -850,   -125,
      805,   1835,   2836,   3672,   4227,   4421,   4227,   3672,   2836,
     1835,    805,   -125,   -850,  -1305,  -1472,  -1383,  -1104,   -726,
     -341,    -29,    156,    194,     98,    -92,   -322,   -534,   -683,
     -740,   -700,   -581,   -414,   -241,    -97,    -10,      7,    -40,
     -133,   -244,   -344,   -409,   -425,   -391,   -317,   -219,   -122,
      -44,      1,	0
};
