/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 31-Oct-2020 19:00:34
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 83
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 83;
const int16_T B[84] = {
      282,    317,    352,    386,    419,    449,    476,    499,    519,
      533,    543,    546,    543,    534,    518,    494,    464,    426,
      381,    330,    272,    209,    140,     66,    -11,    -92,   -174,
     -258,   -342,   -426,   -507,   -585,   -660,   -729,   -793,   -850,
     -900,   -942,   -975,   -999,  -1013,  32767,  -1013,   -999,   -975,
     -942,   -900,   -850,   -793,   -729,   -660,   -585,   -507,   -426,
     -342,   -258,   -174,    -92,    -11,     66,    140,    209,    272,
      330,    381,    426,    464,    494,    518,    534,    543,    546,
      543,    533,    519,    499,    476,    449,    419,    386,    352,
      317,    282,	0
};
