/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 31-Oct-2020 18:07:27
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 87
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 87;
const int16_T B[88] = {
     -153,   -162,   -171,   -181,   -190,   -200,   -209,   -219,   -229,
     -239,   -249,   -259,   -269,   -279,   -288,   -298,   -308,   -317,
     -326,   -336,   -345,   -353,   -362,   -370,   -378,   -386,   -393,
     -400,   -407,   -413,   -419,   -425,   -430,   -435,   -440,   -444,
     -447,   -450,   -453,   -455,   -457,   -458,   -458,  32161,   -458,
     -458,   -457,   -455,   -453,   -450,   -447,   -444,   -440,   -435,
     -430,   -425,   -419,   -413,   -407,   -400,   -393,   -386,   -378,
     -370,   -362,   -353,   -345,   -336,   -326,   -317,   -308,   -298,
     -288,   -279,   -269,   -259,   -249,   -239,   -229,   -219,   -209,
     -200,   -190,   -181,   -171,   -162,   -153,	0
};
