/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 31-Oct-2020 17:39:08
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 83
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 83;
const int16_T B[84] = {
      163,    126,     54,    -38,   -130,   -198,   -224,   -196,   -116,
        0,    128,    236,    296,    289,    208,     67,   -105,   -271,
     -386,   -418,   -349,   -183,     50,    300,    509,    618,    585,
      398,     76,   -323,   -716,  -1004,  -1093,   -912,   -429,    337,
     1320,   2408,   3463,   4345,   4930,   5135,   4930,   4345,   3463,
     2408,   1320,    337,   -429,   -912,  -1093,  -1004,   -716,   -323,
       76,    398,    585,    618,    509,    300,     50,   -183,   -349,
     -418,   -386,   -271,   -105,     67,    208,    289,    296,    236,
      128,      0,   -116,   -196,   -224,   -198,   -130,    -38,     54,
      126,    163,	0
};
