/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
 * Generated on: 18-Oct-2020 00:48:28
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 147
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s33,30 -> [-4 4)
 *   Product         : s31,30 -> [-1 1)
 *   Accumulator     : s33,30 -> [-4 4)
 *   Round Mode      : round
 *   Overflow Mode   : saturate
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /home/cliff/MATLAB/R2018b/extern/include/tmwtypes.h 
 */
const int BL = 147;
const int16_T coef[147] = {
       -3,      4,     -4,      4,     -4,      2,     -1,     -2,      5,
       -8,     12,    -16,     19,    -22,     24,    -25,     23,    -20,
       14,     -6,     -3,     15,    -28,     41,    -53,     64,    -73,
       78,    -79,     75,    -64,     48,    -27,      0,     31,    -64,
       98,   -131,    160,   -182,    197,   -200,    191,   -169,    134,
      -84,     23,     49,   -127,    208,   -287,    360,   -421,    464,
     -484,    477,   -438,    366,   -258,    115,     63,   -271,    505,
     -760,   1027,  -1300,   1568,  -1824,   2059,  -2263,   2431,  -2555,
     2631,  32767,   2631,  -2555,   2431,  -2263,   2059,  -1824,   1568,
    -1300,   1027,   -760,    505,   -271,     63,    115,   -258,    366,
     -438,    477,   -484,    464,   -421,    360,   -287,    208,   -127,
       49,     23,    -84,    134,   -169,    191,   -200,    197,   -182,
      160,   -131,     98,    -64,     31,      0,    -27,     48,    -64,
       75,    -79,     78,    -73,     64,    -53,     41,    -28,     15,
       -3,     -6,     14,    -20,     23,    -25,     24,    -22,     19,
      -16,     12,     -8,      5,     -2,     -1,      2,     -4,      4,
       -4,      4,     -3
};
