/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 22-Oct-2020 13:53:42
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 175
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 176;
const q15_t B[176] = {
      140,    148,    155,    163,    171,    178,    186,    193,    200,
      207,    213,    219,    225,    231,    236,    240,    244,    248,
      251,    254,    256,    257,    258,    259,    258,    257,    255,
      253,    250,    246,    241,    236,    230,    223,    215,    207,
      198,    188,    178,    167,    155,    143,    130,    116,    102,
       87,     72,     56,     39,     23,      6,    -12,    -29,    -47,
      -65,    -84,   -102,   -121,   -139,   -158,   -176,   -194,   -212,
     -230,   -248,   -265,   -282,   -299,   -315,   -330,   -345,   -359,
     -373,   -386,   -398,   -410,   -420,   -430,   -439,   -448,   -455,
     -461,   -467,   -471,   -475,   -477,   -479,  32767,   -479,   -477,
     -475,   -471,   -467,   -461,   -455,   -448,   -439,   -430,   -420,
     -410,   -398,   -386,   -373,   -359,   -345,   -330,   -315,   -299,
     -282,   -265,   -248,   -230,   -212,   -194,   -176,   -158,   -139,
     -121,   -102,    -84,    -65,    -47,    -29,    -12,      6,     23,
       39,     56,     72,     87,    102,    116,    130,    143,    155,
      167,    178,    188,    198,    207,    215,    223,    230,    236,
      241,    246,    250,    253,    255,    257,    258,    259,    258,
      257,    256,    254,    251,    248,    244,    240,    236,    231,
      225,    219,    213,    207,    200,    193,    186,    178,    171,
      163,    155,    148,    140,	0
};
