/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 22-Oct-2020 11:12:45
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 124
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 124;
const q15_t B[124] = {
     -100,    -17,     18,    -70,   -149,    -90,      9,    -29,   -162,
     -180,    -51,      5,   -127,   -248,   -160,     -8,    -60,   -259,
     -287,    -94,     -6,   -197,   -378,   -249,    -19,    -89,   -380,
     -425,   -137,      3,   -273,   -543,   -354,     -1,    -93,   -528,
     -601,   -161,     70,   -344,   -768,   -477,     96,    -28,   -732,
     -868,   -127,    303,   -399,  -1181,   -667,    463,    283,  -1191,
    -1579,    164,   1449,   -429,  -3340,  -1813,   5623,  12985,  12985,
     5623,  -1813,  -3340,   -429,   1449,    164,  -1579,  -1191,    283,
      463,   -667,  -1181,   -399,    303,   -127,   -868,   -732,    -28,
       96,   -477,   -768,   -344,     70,   -161,   -601,   -528,    -93,
       -1,   -354,   -543,   -273,      3,   -137,   -425,   -380,    -89,
      -19,   -249,   -378,   -197,     -6,    -94,   -287,   -259,    -60,
       -8,   -160,   -248,   -127,      5,    -51,   -180,   -162,    -29,
        9,    -90,   -149,    -70,     18,    -17,   -100
};
