/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 22-Oct-2020 11:06:33
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 125
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 126;
const q15_t B[126] = {
      -44,    -49,    -53,    -58,    -63,    -69,    -74,    -80,    -86,
      -92,    -98,   -105,   -112,   -118,   -126,   -133,   -140,   -148,
     -155,   -163,   -171,   -179,   -187,   -195,   -203,   -211,   -219,
     -227,   -235,   -243,   -252,   -260,   -268,   -276,   -283,   -291,
     -299,   -306,   -313,   -321,   -328,   -334,   -341,   -347,   -353,
     -359,   -365,   -370,   -375,   -380,   -384,   -388,   -392,   -395,
     -398,   -401,   -403,   -405,   -407,   -408,   -409,   -410,  32400,
     -410,   -409,   -408,   -407,   -405,   -403,   -401,   -398,   -395,
     -392,   -388,   -384,   -380,   -375,   -370,   -365,   -359,   -353,
     -347,   -341,   -334,   -328,   -321,   -313,   -306,   -299,   -291,
     -283,   -276,   -268,   -260,   -252,   -243,   -235,   -227,   -219,
     -211,   -203,   -195,   -187,   -179,   -171,   -163,   -155,   -148,
     -140,   -133,   -126,   -118,   -112,   -105,    -98,    -92,    -86,
      -80,    -74,    -69,    -63,    -58,    -53,    -49,    -44,	0
};
