/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 22-Oct-2020 10:59:46
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 146
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 146;
const q15_t B[146] = {
       10,     61,      7,    -64,    -26,     62,     47,    -53,    -67,
       38,     84,    -16,    -95,    -11,     99,     41,    -95,    -73,
       81,    102,    -57,   -127,     23,    144,     17,   -150,    -63,
      142,    110,   -121,   -154,     84,    191,    -34,   -216,    -28,
      225,     97,   -215,   -169,    183,    237,   -128,   -296,     51,
      339,     45,   -357,   -157,    346,    277,   -300,   -399,    215,
      512,    -86,   -606,    -87,    669,    307,   -688,   -577,    643,
      907,   -508,  -1319,    232,   1884,    323,  -2849,  -1723,   5837,
    13625,  13625,   5837,  -1723,  -2849,    323,   1884,    232,  -1319,
     -508,    907,    643,   -577,   -688,    307,    669,    -87,   -606,
      -86,    512,    215,   -399,   -300,    277,    346,   -157,   -357,
       45,    339,     51,   -296,   -128,    237,    183,   -169,   -215,
       97,    225,    -28,   -216,    -34,    191,     84,   -154,   -121,
      110,    142,    -63,   -150,     17,    144,     23,   -127,    -57,
      102,     81,    -73,    -95,     41,     99,    -11,    -95,    -16,
       84,     38,    -67,    -53,     47,     62,    -26,    -64,      7,
       61,     10
};
