/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 05-Nov-2020 15:23:03
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 76
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 76;
const q15_t B[76] = {
       -2,    -61,   -160,   -279,   -386,   -453,   -459,   -399,   -287,
     -156,    -44,      9,    -23,   -143,   -329,   -538,   -714,   -803,
     -772,   -619,   -373,   -100,    122,    216,    131,   -142,   -558,
    -1024,  -1417,  -1605,  -1479,   -985,   -137,    978,   2208,   3367,
     4268,   4760,   4760,   4268,   3367,   2208,    978,   -137,   -985,
    -1479,  -1605,  -1417,  -1024,   -558,   -142,    131,    216,    122,
     -100,   -373,   -619,   -772,   -803,   -714,   -538,   -329,   -143,
      -23,      9,    -44,   -156,   -287,   -399,   -459,   -453,   -386,
     -279,   -160,    -61,     -2
};
