/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 05-Nov-2020 15:38:19
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 77
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 77;
const int16_T B[77] = {
      290,    332,    373,    414,    452,    488,    519,    547,    568,
      583,    591,    591,    583,    566,    540,    505,    461,    408,
      346,    276,    199,    116,     26,    -67,   -164,   -263,   -362,
     -460,   -555,   -647,   -733,   -813,   -885,   -948,  -1001,  -1043,
    -1074,  -1093,  32767,  -1093,  -1074,  -1043,  -1001,   -948,   -885,
     -813,   -733,   -647,   -555,   -460,   -362,   -263,   -164,    -67,
       26,    116,    199,    276,    346,    408,    461,    505,    540,
      566,    583,    591,    591,    583,    568,    547,    519,    488,
      452,    414,    373,    332,    290
};
