/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 29-Oct-2020 16:47:23
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 89
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 89;
const int16_T B[90] = {
     -151,   -160,   -169,   -178,   -187,   -196,   -205,   -215,   -224,
     -234,   -243,   -252,   -262,   -271,   -281,   -290,   -299,   -308,
     -317,   -326,   -334,   -343,   -351,   -359,   -366,   -374,   -381,
     -388,   -395,   -401,   -407,   -412,   -418,   -423,   -427,   -431,
     -435,   -438,   -441,   -443,   -445,   -447,   -448,   -449,  32466,
     -449,   -448,   -447,   -445,   -443,   -441,   -438,   -435,   -431,
     -427,   -423,   -418,   -412,   -407,   -401,   -395,   -388,   -381,
     -374,   -366,   -359,   -351,   -343,   -334,   -326,   -317,   -308,
     -299,   -290,   -281,   -271,   -262,   -252,   -243,   -234,   -224,
     -215,   -205,   -196,   -187,   -178,   -169,   -160,   -151,	0
};
