/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 05-Nov-2020 15:33:38
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 76
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */


 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 76;
const q15_t B[76] = {
      176,    126,     33,    -79,   -180,   -238,   -231,   -155,    -25,
      127,    257,    326,    305,    191,      7,   -201,   -374,   -456,
     -412,   -239,     30,    328,    571,    680,    599,    321,   -110,
     -594,  -1001,  -1193,  -1055,   -530,    368,   1546,   2844,   4067,
     5018,   5537,   5537,   5018,   4067,   2844,   1546,    368,   -530,
    -1055,  -1193,  -1001,   -594,   -110,    321,    599,    680,    571,
      328,     30,   -239,   -412,   -456,   -374,   -201,      7,    191,
      305,    326,    257,    127,    -25,   -155,   -231,   -238,   -180,
      -79,     33,    126,    176
};
