/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
 * Generated on: 22-Oct-2020 12:57:58
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 129
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s30,30 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /home/cliff/MATLAB/R2018b/extern/include/tmwtypes.h 
 */
const int BL = 129;
const int16_T B[129] = {
      -50,      5,     61,     59,     -5,    -71,    -68,      6,     82,
       79,     -6,    -94,    -91,      7,    107,    105,     -7,   -122,
     -120,      8,    139,    137,     -9,   -158,   -156,      9,    180,
      178,     -9,   -204,   -204,     10,    233,    234,    -10,   -267,
     -269,     11,    308,    312,    -11,   -358,   -366,     11,    422,
      436,    -12,   -507,   -530,     12,    626,    665,    -12,   -807,
     -879,     12,   1120,   1271,    -12,  -1803,  -2244,     12,   4517,
     9021,  10905,   9021,   4517,     12,  -2244,  -1803,    -12,   1271,
     1120,     12,   -879,   -807,    -12,    665,    626,     12,   -530,
     -507,    -12,    436,    422,     11,   -366,   -358,    -11,    312,
      308,     11,   -269,   -267,    -10,    234,    233,     10,   -204,
     -204,     -9,    178,    180,      9,   -156,   -158,     -9,    137,
      139,      8,   -120,   -122,     -7,    105,    107,      7,    -91,
      -94,     -6,     79,     82,      6,    -68,    -71,     -5,     59,
       61,      5,    -50
};
